//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpEgitimKampi301.EFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCustomer
    {
        public int CustomeId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerSurname { get; set; }
        public Nullable<decimal> CustomerBalance { get; set; }
    }
}
